server:
  port: ${PORT:5001}

base-url: "/api"

rollbar-token: ${ROLLBAR_TOKEN}

jwt:
  token:
    secret: "eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTY4NDc4NDc1OSwiaWF0IjoxNjg0Nzg0NzU5fQ.Llf5dxlq-cfJaB9heyS2iVdN1YO7_Om0g5RwZrS7o_8"

spring:
  profiles:
    active: dev

  application:
    name: taskManager

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  jpa:
    hibernate:
      ddl-auto: none

springdoc:
  swagger-ui:
    path: "/swagger.html"